In [2]:
import os
import pandas as pd
import numpy as np

# 데이터 전처리

## 데이터 불러오기

In [3]:
df = pd.read_csv('data.csv',engine='python', header = 'infer',encoding = 'euc-kr')

In [5]:
df.head

<bound method NDFrame.head of                 시군구  유형    지번        도로명     용도지역   건축물주용도   도로조건  전용/연면적(㎡)  \
0     서울특별시 강남구 개포동  집합  1***      논현로2길  제2종일반주거  제2종근린생활   8m미만      44.21
1     서울특별시 강남구 개포동  집합   1**        개포로     일반상업  제2종근린생활  25m미만      69.57
2     서울특별시 강남구 개포동  일반  1***      논현로8길  제2종일반주거  제2종근린생활   8m미만     428.94
3     서울특별시 강남구 개포동  집합    1*        개포로     일반상업  제1종근린생활  25m이상      13.85
4     서울특별시 강남구 개포동  일반  1***       양재대로  제3종일반주거  제1종근린생활  25m이상    1092.54
5     서울특별시 강남구 개포동  일반  1***     개포로22길  제2종일반주거  제2종근린생활  25m미만     792.35
6     서울특별시 강남구 개포동  일반  1***     논현로20길      준주거  제2종근린생활   8m미만     770.62
7     서울특별시 강남구 개포동  집합    1*    개포로109길     일반상업  제1종근린생활  25m미만      35.12
8     서울특별시 강남구 개포동  집합    1*    개포로109길     일반상업  제1종근린생활  25m미만      91.11
9     서울특별시 강남구 개포동  집합    1*    개포로109길     일반상업  제1종근린생활  25m미만     590.01
10    서울특별시 강남구 개포동  집합    1*        개포로  제3종일반주거  제2종근린생활  25m이상     847.74
11    서울특별시 강남구 개포동  집합   1**        삼성로     일반상업       판매  25m이상      13.10
12    서울특별시 강남구 개포동  집합    1*        개포로     일반상업       업무  25m이상      14.14
13    서울특별시 강남구 개포동  집합   1**        삼성로     일반상업  제2종근린생활  25m이상      10.61
14    서울특별시 강남구 개포동  일반  1***        개포로  제3종일반주거  제1종근린생활  25m미만    1156.80
15    서울특별시 강남구 개포동  집합   1**        개포로  제3종일반주거  제1종근린생활  25m이상      11.34
16    서울특별시 강남구 개포동  집합   6**        언주로  제3종일반주거  제1종근린생활  25m이상      65.20
17    서울특별시 강남구 개포동  집합    1*        개포로     일반상업       업무  25m이상      32.44
18    서울특별시 강남구 개포동  집합   1**        개포로  제2종일반주거  제1종근린생활  25m미만      18.24
19    서울특별시 강남구 개포동  집합   1**        개포로     일반상업  제2종근린생활  25m미만      25.94
20    서울특별시 강남구 개포동  집합    1*        개포로     일반상업       업무  25m이상      32.86
21    서울특별시 강남구 개포동  집합   1**        개포로  제3종일반주거  제2종근린생활  25m이상      14.40
22    서울특별시 강남구 개포동  집합    1*        개포로     일반상업       업무  25m이상      31.91
23    서울특별시 강남구 개포동  집합   1**      삼성로4길  제3종일반주거       판매  25m이상      16.56
24    서울특별시 강남구 개포동  집합    1*        개포로     일반상업       업무  25m이상      31.91
25    서울특별시 강남구 개포동  집합   1**      삼성로4길  제3종일반주거  제1종근린생활  25m이상      16.56
26    서울특별시 강남구 개포동  집합   1**      삼성로4길  제3종일반주거  제1종근린생활  25m이상      16.56
27    서울특별시 강남구 개포동  집합    1*        개포로     일반상업  제1종근린생활  25m이상      10.63
28    서울특별시 강남구 개포동  집합   1**        개포로     일반상업  제2종근린생활  25m미만      73.98
29    서울특별시 강남구 개포동  집합   6**        개포로  제3종일반주거       판매  25m이상      36.60
...             ...  ..   ...        ...      ...      ...    ...        ...
7350  서울특별시 중랑구 상봉동  집합   3**    봉화산로30길  제2종일반주거  제1종근린생활      -      66.81
7351  서울특별시 중랑구 상봉동  집합   3**    봉화산로30길  제2종일반주거  제1종근린생활  12m미만      29.40
7352  서울특별시 중랑구 상봉동  집합   3**    봉화산로30길  제2종일반주거  제1종근린생활  12m미만      49.68
7353  서울특별시 중랑구 상봉동  집합   3**    봉화산로30길  제2종일반주거  제2종근린생활      -      37.76
7354  서울특별시 중랑구 상봉동  집합   3**    동일로126길  제2종일반주거  제2종근린생활      -      38.26
7355  서울특별시 중랑구 상봉동  집합   3**    봉화산로30길  제2종일반주거  제2종근린생활      -      35.77
7356  서울특별시 중랑구 신내동  집합   3**        신내로  제3종일반주거  제2종근린생활  25m이상      30.60
7357  서울특별시 중랑구 신내동  집합   7**        신내로  제3종일반주거  제2종근린생활  25m이상      21.27
7358  서울특별시 중랑구 신내동  일반   4**  용마산로129나길  제3종일반주거  제1종근린생활   8m미만      94.62
7359  서울특별시 중랑구 신내동  집합   6**        신내로      준주거  제2종근린생활  25m이상      42.90
7360  서울특별시 중랑구 신내동  집합   6**        신내로      준주거  제1종근린생활  25m이상      36.66
7361  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      14.82
7362  서울특별시 중랑구 신내동  집합   6**        신내로      준주거     교육연구  25m이상      90.87
7363  서울특별시 중랑구 신내동  집합   5**    봉화산로56길  제3종일반주거  제1종근린생활  12m미만      20.96
7364  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      18.33
7365  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      37.49
7366  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      51.66
7367  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      19.89
7368  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      19.89
7369  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상       9.40
7370  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업  제2종근린생활  25m이상      24.18
7371  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      11.70
7372  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상      11.70
7373  서울특별시 중랑구 신내동  집합   6**       봉화산로     일반상업       판매  25m이상       9.72
7374  서울특별시 중랑구 중화동  일반   1**       봉화산로  제2종일반주거  제2종근린생활  25m미만     100.99
7375  서울특별시 중랑구 중화동  집합   3**    동일로129길  제2종일반주거       기타  25m미만      11.27
7376  서울특별시 중랑구 중화동  일반   2**       중랑역로      준주거       숙박  25m미만    1373.81
7377  서울특별시 중랑구 중화동  일반   1**   봉화산로26가길  제2종일반주거       기타   8m미만     400.14
7378  서울특별시 중랑구 중화동  집합    1*    봉화산로27길  제2종일반주거       판매   8m미만      25.13
7379  서울특별시 중랑구 중화동  일반   3**       중랑역로  제2종일반주거  제2종근린생활  25m미만      79.20

     거래금액(만원)     층    계약년월    계약일    건축년도
0      26,000   NaN  201807  21~31  2017.0
1      53,000   3.0  201808  11~20  1984.0
2     195,000   NaN  201808  11~20  1993.0
3       8,800   NaN  201808  11~20  1997.0
4     445,000   NaN  201808  21~31  1993.0
5     375,000   NaN  201808  21~31  1990.0
6     400,000   NaN  201808  21~31  1992.0
7      18,500   5.0  201808  21~31  1998.0
8      51,200   5.0  201808  21~31  1998.0
9     320,300   4.0  201808  21~31  1998.0
10    390,000   5.0  201809  11~20  1995.0
11      2,200   NaN  201809   1~10  1984.0
12     12,300   NaN  201809   1~10  1997.0
13      1,500   NaN  201809  21~30  1984.0
14    520,000   NaN  201810   1~10  1992.0
15     17,450   1.0  201810  21~31  1983.0
16     19,000   NaN  201810  21~31  1984.0
17     19,000   5.0  201810  21~31  1997.0
18     50,000   1.0  201811  11~20  1987.0
19     85,000   NaN  201811   1~10  1984.0
20     22,800  15.0  201811  21~30  1997.0
21     21,000   NaN  201812  11~20  1983.0
22     21,900  15.0  201812  11~20  1997.0
23     22,000   2.0  201812   1~10  1983.0
24     20,500  14.0  201812   1~10  1997.0
25     48,000   1.0  201812   1~10  1983.0
26     48,000   NaN  201812   1~10  1983.0
27      7,800   NaN  201812  21~31  1997.0
28     50,000   5.0  201812  21~31  1984.0
29     82,170   1.0  201812  21~31  1984.0
...       ...   ...     ...    ...     ...
7350   22,949   1.0  201812  21~31  2018.0
7351   14,098   1.0  201812  21~31  2018.0
7352   24,274   1.0  201812  21~31  2018.0
7353   13,833   1.0  201812  21~31  2018.0
7354   13,197   1.0  201812  21~31  2018.0
7355   12,296   1.0  201812  21~31  2018.0
7356   38,800   1.0  201807  11~20  1993.0
7357    7,000   1.0  201808  11~20  1994.0
7358   59,200   NaN  201808   1~10  1995.0
7359   49,500   1.0  201808  21~31  2003.0
7360   59,000   1.0  201809  11~20  2003.0
7361    1,300   NaN  201809   1~10  1999.0
7362   41,500   3.0  201809   1~10  2003.0
7363    3,400   2.0  201810  11~20  1994.0
7364    4,600   2.0  201810  21~31  1999.0
7365    5,260   NaN  201811  11~20  1999.0
7366    6,500   NaN  201811   1~10  1999.0
7367    3,400   3.0  201811   1~10  1999.0
7368    3,700   3.0  201811  21~30  1999.0
7369    1,300   3.0  201811  21~30  1999.0
7370    3,900   6.0  201812  11~20  1999.0
7371    5,900   NaN  201812   1~10  1999.0
7372    1,200   NaN  201812   1~10  1999.0
7373      900   NaN  201812   1~10  1999.0
7374   50,500   NaN  201808  11~20  1991.0
7375    1,540   1.0  201808  11~20  2005.0
7376  660,000   NaN  201808  11~20  1979.0
7377  143,000   NaN  201808  21~31  2012.0
7378    2,800   2.0  201811  21~30  1991.0
7379  100,700   NaN  201812  21~31  1997.0

[7380 rows x 13 columns]>

In [6]:
df.describe()

          전용/연면적(㎡)            층           계약년월         건축년도
count   7380.000000  2821.000000    7380.000000  7235.000000
mean     254.535687     5.353421  201809.680352  1998.514029
std     1664.459235     9.604754       1.810547    43.098500
min        3.320000     1.000000  201807.000000     0.000000
25%       13.917500     1.000000  201808.000000  1990.000000
50%       36.400000     2.000000  201810.000000  2004.000000
75%       97.150000     5.000000  201812.000000  2008.000000
max    81117.280000    90.000000  201812.000000  2019.000000

In [33]:
df.isnull().sum()

시군구             0
유형              0
지번              0
도로명             0
용도지역            0
건축물주용도          0
도로조건            0
전용/연면적(㎡)       0
거래금액(만원)        0
층            4559
계약년월            0
계약일             0
건축년도          145
dtype: int64

### 열 이름 변경

In [4]:
df.columns

Index(['시군구', '유형', '지번', '도로명', '용도지역', '건축물주용도', '도로조건', '전용/연면적(㎡)',
       '거래금액(만원)', '층', '계약년월', '계약일', '건축년도'],
      dtype='object')

In [5]:
df.columns = ['city','type','lot_num','road_name','usage_area','arch_use','road_condition','exclusive_area','amount','floor','yy/mm','dd','built_year']

In [6]:
df.head()

,city,type,lot_num,road_name,usage_area,arch_use,road_condition,exclusive_area,amount,floor,yy/mm,dd,built_year
0,서울특별시 강남구 개포동,집합,1***,논현로2길,제2종일반주거,제2종근린생활,8m미만,44.21,"26,000",NaN,201807,21~31,2017.0
1,서울특별시 강남구 개포동,집합,1**,개포로,일반상업,제2종근린생활,25m미만,69.57,"53,000",3.0,201808,11~20,1984.0
2,서울특별시 강남구 개포동,일반,1***,논현로8길,제2종일반주거,제2종근린생활,8m미만,428.94,"195,000",NaN,201808,11~20,1993.0
3,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,제1종근린생활,25m이상,13.85,"8,800",NaN,201808,11~20,1997.0
4,서울특별시 강남구 개포동,일반,1***,양재대로,제3종일반주거,제1종근린생활,25m이상,1092.54,"445,000",NaN,201808,21~31,1993.0

In [39]:
df['si'] = df['city'].str[0:5]

## code 불러오기

In [34]:
code = pd.read_csv('code.csv',engine='python', header = 'infer',encoding = 'euc-kr')

In [38]:
code.head()

   hang_dond_code     si   gu   dong  bup_doing_code bup_dong
0      1111051500  서울특별시  종로구  청운효자동      1111010100      청운동
1      1111051500  서울특별시  종로구  청운효자동      1111010200      신교동
2      1111051500  서울특별시  종로구  청운효자동      1111010300      궁정동
3      1111051500  서울특별시  종로구  청운효자동      1111010400      효자동
4      1111051500  서울특별시  종로구  청운효자동      1111010500      창성동

In [36]:
code = code.drop(['생성일자', '말소일자'],axis=1)

In [37]:
code.columns = ['hang_dond_code', 'si', 'gu', 'dong', 'bup_doing_code', 'bup_dong']

In [28]:
code['city'] = code['si-do'] + " " + code['gu'] + " " + code['dong']

## code와 실거래 data 합치기

In [30]:
pd.merge(df, code, how='left', on='city')

,city,type,lot_num,road_name,usage_area,arch_use,road_condition,exclusive_area,amount,floor,yy/mm,dd,built_year,hang_dond_code,si-do,gu,dong,bup_doing_code,bup_dong
0,서울특별시 강남구 개포동,집합,1***,논현로2길,제2종일반주거,제2종근린생활,8m미만,44.21,"26,000",NaN,201807,21~31,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
1,서울특별시 강남구 개포동,집합,1**,개포로,일반상업,제2종근린생활,25m미만,69.57,"53,000",3.0,201808,11~20,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
2,서울특별시 강남구 개포동,일반,1***,논현로8길,제2종일반주거,제2종근린생활,8m미만,428.94,"195,000",NaN,201808,11~20,1993.0,NaN,NaN,NaN,NaN,NaN,NaN
3,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,제1종근린생활,25m이상,13.85,"8,800",NaN,201808,11~20,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
4,서울특별시 강남구 개포동,일반,1***,양재대로,제3종일반주거,제1종근린생활,25m이상,1092.54,"445,000",NaN,201808,21~31,1993.0,NaN,NaN,NaN,NaN,NaN,NaN
5,서울특별시 강남구 개포동,일반,1***,개포로22길,제2종일반주거,제2종근린생활,25m미만,792.35,"375,000",NaN,201808,21~31,1990.0,NaN,NaN,NaN,NaN,NaN,NaN
6,서울특별시 강남구 개포동,일반,1***,논현로20길,준주거,제2종근린생활,8m미만,770.62,"400,000",NaN,201808,21~31,1992.0,NaN,NaN,NaN,NaN,NaN,NaN
7,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,35.12,"18,500",5.0,201808,21~31,1998.0,NaN,NaN,NaN,NaN,NaN,NaN
8,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,91.11,"51,200",5.0,201808,21~31,1998.0,NaN,NaN,NaN,NaN,NaN,NaN
9,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,590.01,"320,300",4.0,201808,21~31,1998.0,NaN,NaN,NaN,NaN,NaN,NaN
10,서울특별시 강남구 개포동,집합,1*,개포로,제3종일반주거,제2종근린생활,25m이상,847.74,"390,000",5.0,201809,11~20,1995.0,NaN,NaN,NaN,NaN,NaN,NaN
11,서울특별시 강남구 개포동,집합,1**,삼성로,일반상업,판매,25m이상,13.10,"2,200",NaN,201809,1~10,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
12,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,업무,25m이상,14.14,"12,300",NaN,201809,1~10,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
13,서울특별시 강남구 개포동,집합,1**,삼성로,일반상업,제2종근린생활,25m이상,10.61,"1,500",NaN,201809,21~30,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
14,서울특별시 강남구 개포동,일반,1***,개포로,제3종일반주거,제1종근린생활,25m미만,1156.80,"520,000",NaN,201810,1~10,1992.0,NaN,NaN,NaN,NaN,NaN,NaN
15,서울특별시 강남구 개포동,집합,1**,개포로,제3종일반주거,제1종근린생활,25m이상,11.34,"17,450",1.0,201810,21~31,1983.0,NaN,NaN,NaN,NaN,NaN,NaN
16,서울특별시 강남구 개포동,집합,6**,언주로,제3종일반주거,제1종근린생활,25m이상,65.20,"19,000",NaN,201810,21~31,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
17,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,업무,25m이상,32.44,"19,000",5.0,201810,21~31,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
18,서울특별시 강남구 개포동,집합,1**,개포로,제2종일반주거,제1종근린생활,25m미만,18.24,"50,000",1.0,201811,11~20,1987.0,NaN,NaN,NaN,NaN,NaN,NaN
19,서울특별시 강남구 개포동,집합,1**,개포로,일반상업,제2종근린생활,25m미만,25.94,"85,000",NaN,201811,1~10,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
20,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,업무,25m이상,32.86,"22,800",15.0,201811,21~30,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
21,서울특별시 강남구 개포동,집합,1**,개포로,제3종일반주거,제2종근린생활,25m이상,14.40,"21,000",NaN,201812,11~20,1983.0,NaN,NaN,NaN,NaN,NaN,NaN
22,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,업무,25m이상,31.91,"21,900",15.0,201812,11~20,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
23,서울특별시 강남구 개포동,집합,1**,삼성로4길,제3종일반주거,판매,25m이상,16.56,"22,000",2.0,201812,1~10,1983.0,NaN,NaN,NaN,NaN,NaN,NaN
24,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,업무,25m이상,31.91,"20,500",14.0,201812,1~10,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
25,서울특별시 강남구 개포동,집합,1**,삼성로4길,제3종일반주거,제1종근린생활,25m이상,16.56,"48,000",1.0,201812,1~10,1983.0,NaN,NaN,NaN,NaN,NaN,NaN
26,서울특별시 강남구 개포동,집합,1**,삼성로4길,제3종일반주거,제1종근린생활,25m이상,16.56,"48,000",NaN,201812,1~10,1983.0,NaN,NaN,NaN,NaN,NaN,NaN
27,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,제1종근린생활,25m이상,10.63,"7,800",NaN,201812,21~31,1997.0,NaN,NaN,NaN,NaN,NaN,NaN
28,서울특별시 강남구 개포동,집합,1**,개포로,일반상업,제2종근린생활,25m미만,73.98,"50,000",5.0,201812,21~31,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
29,서울특별시 강남구 개포동,집합,6**,개포로,제3종일반주거,판매,25m이상,36.60,"82,170",1.0,201812,21~31,1984.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8492,서울특별시 중랑구 상봉동,집합,3**,봉화산로30길,제2종일반주거,제1종근린생활,-,66.81,"22,949",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8493,서울특별시 중랑구 상봉동,집합,3**,봉화산로30길,제2종일반주거,제1종근린생활,12m미만,29.40,"14,098",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8494,서울특별시 중랑구 상봉동,집합,3**,봉화산로30길,제2종일반주거,제1종근린생활,12m미만,49.68,"24,274",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8495,서울특별시 중랑구 상봉동,집합,3**,봉화산로30길,제2종일반주거,제2종근린생활,-,37.76,"13,833",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8496,서울특별시 중랑구 상봉동,집합,3**,동일로126길,제2종일반주거,제2종근린생활,-,38.26,"13,197",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8497,서울특별시 중랑구 상봉동,집합,3**,봉화산로30길,제2종일반주거,제2종근린생활,-,35.77,"12,296",1.0,201812,21~31,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
8498,서울특별시 중랑구 신내동,집합,3**,신내로,제3종일반주거,제2종근린생활,25m이상,30.60,"38,800",1.0,201807,11~20,1993.0,NaN,NaN,NaN,NaN,NaN,NaN
8499,서울특별시 중랑구 신내동,집합,7**,신내로,제3종일반주거,제2종근린생활,25m이상,21.27,"7,000",1.0,201808,11~20,1994.0,NaN,NaN,NaN,NaN,NaN,NaN
8500,서울특별시 중랑구 신내동,일반,4**,용마산로129나길,제3종일반주거,제1종근린생활,8m미만,94.62,"59,200",NaN,201808,1~10,1995.0,NaN,NaN,NaN,NaN,NaN,NaN
8501,서울특별시 중랑구 신내동,집합,6**,신내로,준주거,제2종근린생활,25m이상,42.90,"49,500",1.0,201808,21~31,2003.0,NaN,NaN,NaN,NaN,NaN,NaN
8502,서울특별시 중랑구 신내동,집합,6**,신내로,준주거,제1종근린생활,25m이상,36.66,"59,000",1.0,201809,11~20,2003.0,NaN,NaN,NaN,NaN,NaN,NaN
8503,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,14.82,"1,300",NaN,201809,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8504,서울특별시 중랑구 신내동,집합,6**,신내로,준주거,교육연구,25m이상,90.87,"41,500",3.0,201809,1~10,2003.0,NaN,NaN,NaN,NaN,NaN,NaN
8505,서울특별시 중랑구 신내동,집합,5**,봉화산로56길,제3종일반주거,제1종근린생활,12m미만,20.96,"3,400",2.0,201810,11~20,1994.0,NaN,NaN,NaN,NaN,NaN,NaN
8506,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,18.33,"4,600",2.0,201810,21~31,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8507,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,37.49,"5,260",NaN,201811,11~20,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8508,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,51.66,"6,500",NaN,201811,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8509,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,19.89,"3,400",3.0,201811,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8510,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,19.89,"3,700",3.0,201811,21~30,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8511,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,9.40,"1,300",3.0,201811,21~30,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8512,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,제2종근린생활,25m이상,24.18,"3,900",6.0,201812,11~20,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8513,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,11.70,"5,900",NaN,201812,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8514,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,11.70,"1,200",NaN,201812,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8515,서울특별시 중랑구 신내동,집합,6**,봉화산로,일반상업,판매,25m이상,9.72,900,NaN,201812,1~10,1999.0,NaN,NaN,NaN,NaN,NaN,NaN
8516,서울특별시 중랑구 중화동,일반,1**,봉화산로,제2종일반주거,제2종근린생활,25m미만,100.99,"50,500",NaN,201808,11~20,1991.0,NaN,NaN,NaN,NaN,NaN,NaN
8517,서울특별시 중랑구 중화동,집합,3**,동일로129길,제2종일반주거,기타,25m미만,11.27,"1,540",1.0,201808,11~20,2005.0,NaN,NaN,NaN,NaN,NaN,NaN
8518,서울특별시 중랑구 중화동,일반,2**,중랑역로,준주거,숙박,25m미만,1373.81,"660,000",NaN,201808,11~20,1979.0,NaN,NaN,NaN,NaN,NaN,NaN
8519,서울특별시 중랑구 중화동,일반,1**,봉화산로26가길,제2종일반주거,기타,8m미만,400.14,"143,000",NaN,201808,21~31,2012.0,NaN,NaN,NaN,NaN,NaN,NaN
8520,서울특별시 중랑구 중화동,집합,1*,봉화산로27길,제2종일반주거,판매,8m미만,25.13,"2,800",2.0,201811,21~30,1991.0,NaN,NaN,NaN,NaN,NaN,NaN
8521,서울특별시 중랑구 중화동,일반,3**,중랑역로,제2종일반주거,제2종근린생활,25m미만,79.20,"100,700",NaN,201812,21~31,1997.0,NaN,NaN,NaN,NaN,NaN,NaN

## floor=null , 분할

In [53]:
A=df.floor.isnull()

In [67]:
df_floor=df[A==False]
df_floor_null=df[A]

In [68]:
df_floor.head()

,city,type,lot_num,road_name,usage_area,arch_use,road_condition,exclusive_area,amount,floor,yy/mm,dd,built_year
1,서울특별시 강남구 개포동,집합,1**,개포로,일반상업,제2종근린생활,25m미만,69.57,"53,000",3.0,201808,11~20,1984.0
7,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,35.12,"18,500",5.0,201808,21~31,1998.0
8,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,91.11,"51,200",5.0,201808,21~31,1998.0
9,서울특별시 강남구 개포동,집합,1*,개포로109길,일반상업,제1종근린생활,25m미만,590.01,"320,300",4.0,201808,21~31,1998.0
10,서울특별시 강남구 개포동,집합,1*,개포로,제3종일반주거,제2종근린생활,25m이상,847.74,"390,000",5.0,201809,11~20,1995.0

In [69]:
df_floor_null.head()

,city,type,lot_num,road_name,usage_area,arch_use,road_condition,exclusive_area,amount,floor,yy/mm,dd,built_year
0,서울특별시 강남구 개포동,집합,1***,논현로2길,제2종일반주거,제2종근린생활,8m미만,44.21,"26,000",NaN,201807,21~31,2017.0
2,서울특별시 강남구 개포동,일반,1***,논현로8길,제2종일반주거,제2종근린생활,8m미만,428.94,"195,000",NaN,201808,11~20,1993.0
3,서울특별시 강남구 개포동,집합,1*,개포로,일반상업,제1종근린생활,25m이상,13.85,"8,800",NaN,201808,11~20,1997.0
4,서울특별시 강남구 개포동,일반,1***,양재대로,제3종일반주거,제1종근린생활,25m이상,1092.54,"445,000",NaN,201808,21~31,1993.0
5,서울특별시 강남구 개포동,일반,1***,개포로22길,제2종일반주거,제2종근린생활,25m미만,792.35,"375,000",NaN,201808,21~31,1990.0